//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public int Customer_ID_CARD { get; set; }
        public Nullable<double> КолвоБалловЗаЗаказ { get; set; }
        public Nullable<int> Order_ID { get; set; }
        public Nullable<double> ОбщееКоличествоБаллов { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Order Order { get; set; }
    }
}
